description = "Test go builder"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/go:0.1.0"
version = "0.1.0"

[[order]]
[[order.group]]
id = "paketo-buildpacks/go"
version = "0.1.0"

[stack]
id = "io.buildpacks.stacks.bionic"
build-image = "europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/focal/build-image:0.0.1-base-cnb"
run-image = "europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/focal/run-image:0.0.1-base-cnb"
